# version: '3.8'
services:

  laravel-docker:
    container_name: laravel-docker
    build: .
    volumes:
      - ./RestaurantEU:/var/www/html
    ports:
      - 9000:80
    restart: always
  
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: restaurantdb
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
    - 3307:3306

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1